debug: 
  false

server:
  servlet:
    context-path: /api
 
spring:
  application: 
    name:  api
  devtools:
    restart:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true 
    properties:
      hibernate.format_sql: true
      
  h2:
    console:
      enabled: true
      path: /h2/console