debug: 
  false

server:
  servlet:
    context-path: /api
  port: 9090
 
spring:
  application: 
    name:  api
  devtools:
    restart:
      enabled: true
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true 
    properties:
      hibernate.format_sql: true
      
  h2:
    console:
      enabled: true
      path: /h2-console  datasource:    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:alura-forum
    name: sa
    password: 
    data:    - classpath*:database/initial-data.sql